#!/bin/sh

# script local variables
script_path="$(dirname $(realpath -s ${0}))"

# zsh
zsh_src="${script_path}/zsh/.config/zsh"
zsh_dest_zsh="${HOME}/.config/zsh"
zsh_dest_omz="${zsh_dest_zsh}"
zsh_dest_custom_themes="${HOME}/.config/zsh/custom/themes"
zsh_dest_custom_plugins="${HOME}/.config/zsh/custom/plugins"
zsh_plugins="
    https://github.com/zsh-users/zsh-history-substring-search
    https://github.com/zsh-users/zsh-syntax-highlighting
    https://github.com/zsh-users/zsh-completions
    https://github.com/zsh-users/zsh-history-substring-search
"

setup_zsh() {
    if [ -d "${zsh_dest_zsh}" ]; then
       printf '%s' "${zsh_dest_zsh} exists, which indicates a previous installation. Please remove this directory and run the setup again."
       exit 1
    fi

    # delete any files in /etc/zsh
    printf '%s' "[Needs Root Permissions] Deleting files in /etc/zsh"
    run_cmd sudo rm --force --recursive /etc/zsh/*

    # copy zshenv to /etc/zsh
    printf '%s' "[Needs Root Permissions] Copying zshenv to /etc/zsh"
    run_cmd sudo cp "${script_path}/zsh/etc/zsh/zshenv" "/etc/zsh"

    # install oh-my-zsh
    printf '%s' "Installing oh-my-zsh"
    run_cmd git clone "https://github.com/ohmyzsh/ohmyzsh.git" "${zsh_dest_omz}"

    # install plugins for zsh
    printf '%s\n' 'Setting up plugins for ZSH'
    for plugin in ${zsh_plugins}; do
        printf '%s' "  Cloning ${plugin}"
        run_cmd git clone -C "${zsh_dest_custom_plugins}" "${plugin}"
    done

    # installing powerlevel10k
    printf '%s' 'Installing powerlevel10k'
    run_cmd git clone -C "${zsh_dest_custom_themes}" --depth=1 https://github.com/romkatv/powerlevel10k.git

    # linking configuration
    printf '%s' 'Linking personal configuration'
    run_cmd ln -sf "${zsh_src}/.zshrc" "${zsh_dest_zsh}"
}
